// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiFV7SkWlVeVZ2xGwPMpc8oq6MfRYbNMM',
    appId: '1:862971153777:web:fc1ecc508e7da70dabbad0',
    messagingSenderId: '862971153777',
    projectId: 'fintrack-gt',
    authDomain: 'fintrack-gt.firebaseapp.com',
    storageBucket: 'fintrack-gt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIJY8XLlb5Bhsc1hd4pnB14qq6luQ-W9I',
    appId: '1:862971153777:android:2b3f32e77981d69fabbad0',
    messagingSenderId: '862971153777',
    projectId: 'fintrack-gt',
    storageBucket: 'fintrack-gt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuZpGjUy04VegQOzpyu4m5efqkSqp-8qc',
    appId: '1:862971153777:ios:158c6228ec03bf18abbad0',
    messagingSenderId: '862971153777',
    projectId: 'fintrack-gt',
    storageBucket: 'fintrack-gt.firebasestorage.app',
    iosClientId: '862971153777-hr5aonrddjer8k42mrm492vckl530gsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintrackGt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuZpGjUy04VegQOzpyu4m5efqkSqp-8qc',
    appId: '1:862971153777:ios:158c6228ec03bf18abbad0',
    messagingSenderId: '862971153777',
    projectId: 'fintrack-gt',
    storageBucket: 'fintrack-gt.firebasestorage.app',
    iosClientId: '862971153777-hr5aonrddjer8k42mrm492vckl530gsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintrackGt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiFV7SkWlVeVZ2xGwPMpc8oq6MfRYbNMM',
    appId: '1:862971153777:web:c92c30244578d39dabbad0',
    messagingSenderId: '862971153777',
    projectId: 'fintrack-gt',
    authDomain: 'fintrack-gt.firebaseapp.com',
    storageBucket: 'fintrack-gt.firebasestorage.app',
  );
}
